name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Set the branch name

env:
  IMAGE_NAME: snapscrap

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64  # Optional: specify platforms
        push: true
        tags: ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest

